# Site settings
name: ThinkBlog
description:  "Just Thinking ..."

author: Humch
baseurl: ""

meta_description: Humch;个人博客;IT技术;读书
motto: I think, therefore I am

permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# Build settings
markdown: kramdown
