# Site settings
name: ThinkBlog
description:  "Just Thinking ..."

author: lanhq
baseurl: ""

meta_description: lanhq;个人博客;IT技术;读书
motto: ego cogito, ergo sum

permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# Build settings
markdown: kramdown
